version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.22.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: check version
          command: node -v